"""Render the pinned CMMC L2 catalog as Markdown for practitioner review.

The first part is the reconciliation report: provenance, counts, what was not
carried, and every reported discrepancy. The second part is every requirement
and objective with a review checkbox and its verbatim text.

Usage:
    python catalog/cmmc_export.py \
        --catalog catalog/versions/cmmc-l2-ag-v2.13.json \
        --out docs/catalogs/cmmc-l2-ag-v2.13.md

Standard library only.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any


def render(catalog: dict[str, Any]) -> str:
    version = catalog["framework_version"]
    counts = catalog["counts"]
    lines = [
        f"# CMMC Level 2 catalog review: `{version['id']}`",
        "",
        "Generated by `catalog/cmmc_export.py`. Do not edit by hand.",
        "",
        "## Reconciliation report",
        "",
        "### Provenance",
        "",
        f"- Source: {version['source_title']} ({version['source_url']})",
        f"- Source retrieval date: {version['source_retrieved']}",
        f"- Migrated from `{version['migrated_from']}` (entered Git in `{version['migrated_from_commit']}`)",
        f"- Seed SHA-256: `{version['migrated_from_sha256']}`",
        f"- Catalog content SHA-256: `{catalog['content_sha256']}`",
        "",
        "### Counts",
        "",
        f"{counts['domains']} domains, {counts['requirements']} requirements, "
        f"{counts['objectives']} objectives.",
        "",
        "| Domain | Requirements |",
        "|---|---|",
    ]
    lines += [f"| {code} | {n} |" for code, n in counts["by_domain"].items()]
    lines += ["", "### Field authority", ""]
    lines += [f"- `{field}`: {authority}" for field, authority in catalog["field_authority"].items()]
    lines += [
        "",
        "No RainTech practitioner guidance is in this catalog. Issue #31 adds it as a separately attributed layer.",
        "",
        "### Not carried",
        "",
        f"- `objective.evidence_examples`: {catalog['not_carried']['objective.evidence_examples']}",
        f"- Placeholder objectives: {', '.join(catalog['not_carried']['placeholder_objectives'])}",
        "",
        "### Reported discrepancies",
        "",
        "Text is carried verbatim. These extraction artifacts are reported, not corrected.",
        "Each needs a decision before the text is shown to clients.",
        "",
        "| Check | Field | Records | Meaning |",
        "|---|---|---|---|",
    ]
    tally = Counter((d["check"], d["field"]) for d in catalog["discrepancies"])
    for (check, field), n in sorted(tally.items()):
        lines.append(f"| `{check}` | `{field}` | {n} | {catalog['discrepancy_checks'][check]} |")
    by_check: dict[str, list[str]] = {}
    for item in catalog["discrepancies"]:
        if item["check"] in {"lowercase_cui_title", "page_header_leak"}:
            by_check.setdefault(f"{item['check']} ({item['field']})", []).append(item["record_id"])
    for label, ids in sorted(by_check.items()):
        lines += ["", f"**{label}:** {', '.join(ids)}"]
    lines += ["", "## Catalog", ""]
    current_domain = None
    records = catalog["records"]
    for index, record in enumerate(records):
        if record["domain_code"] != current_domain:
            current_domain = record["domain_code"]
            lines += [f"### {current_domain} — {record['work_area']}", ""]
        if record["record_type"] == "requirement":
            lines += [
                f"#### [ ] {record['id']} — {record['title']}",
                "",
                f"> {record['text']}",
                "",
                "<details><summary>Assessment methods, discussion, further discussion</summary>",
                "",
                record["assessment_methods"],
                "",
                record["discussion"],
                "",
                record["further_discussion"],
                "",
                "</details>",
                "",
            ]
        else:
            lines.append(f"- [ ] `{record['citation']}` {record['text']}")
            if index + 1 == len(records) or records[index + 1]["record_type"] == "requirement":
                lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--catalog", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    catalog = json.loads(args.catalog.read_text(encoding="utf-8"))
    args.out.write_text(render(catalog), encoding="utf-8")
    print(args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
